engine_telegraph_r_pods += modbus_nats_kv_client

engine_telegraph_r_pod_modbus_nats_kv_client_network_interfaces += eth0 nats0
engine_telegraph_r_pod_modbus_nats_kv_client_eth0_network = CONTROL
engine_telegraph_r_pod_modbus_nats_kv_client_nats0_network = NATS
