apiVersion: v1
kind: Pod
metadata:
  name: macyste-gui-instruments
spec:
  containers:
    - name: gui-instruments
      image: ${gui_instruments_image}
      env:
      - { name: NATS_URL, value: ${nats_ws_url} }
