FROM debian:11

RUN apt-get update && apt-get install -y git gettext
WORKDIR /usr/local/src
RUN git clone https://github.com/thiagoralves/OpenPLC_v3.git
WORKDIR /usr/local/src/OpenPLC_v3
RUN git checkout d7fa92bd6eb00f012dd1e83e18d219570a45d594
RUN ./install.sh docker
COPY entrypoint.sh ./
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]