NETWORK_NAMES += BRIDGE
NETWORK_NAMES += CONTROL
NETWORK_NAMES += NATS
NETWORK_NAMES += SERIAL
NETWORK_NAMES += MANAGEMENT

BRIDGE_NET_NAME = macyste_bridge
BRIDGE_NET_CIDR = 10.1.5.0/24
BRIDGE_NET_DRIVER = macvlan

CONTROL_NET_NAME = macyste_control
CONTROL_NET_CIDR = 10.1.3.0/24
CONTROL_NET_DRIVER = macvlan

NATS_NET_NAME = macyste_nats
NATS_NET_CIDR = 10.1.4.0/24
NATS_NET_DRIVER = macvlan

SERIAL_NET_NAME = macyste_serial
SERIAL_NET_CIDR = 10.1.2.0/24
SERIAL_NET_DRIVER = macvlan

MANAGEMENT_NET_NAME = macyste_management
MANAGEMENT_NET_CIDR = 192.168.249.0/24
MANAGEMENT_NET_DRIVER = bridge
MANAGEMENT_NET_INTERNAL = true
