radar_converter_asterix_pods += radar_converter

radar_converter_asterix_pod_radar_converter_network_interfaces += eth0 nats0
radar_converter_asterix_pod_radar_converter_eth0_network = BRIDGE
radar_converter_asterix_pod_radar_converter_nats0_network = NATS

