engine_sim_plc_r_pods += modbus_nats_kv_server

engine_sim_plc_r_pod_modbus_nats_kv_server_network_interfaces += eth0 nats0
engine_sim_plc_r_pod_modbus_nats_kv_server_eth0_network = CONTROL
engine_sim_plc_r_pod_modbus_nats_kv_server_nats0_network = NATS
