ARG FEDORA_IMAGE
FROM ${FEDORA_IMAGE}
RUN dnf install -y python3 wireshark-cli && dnf clean all

COPY entrypoint.sh /opt/entrypoint.sh
COPY process_line.py /opt/process_line.py

RUN chmod +x /opt/entrypoint.sh

WORKDIR /opt
ENTRYPOINT [ "/opt/entrypoint.sh" ]
